### ISSUE TITLE
New clone build fails

### ISSUE THREAD

**Issue by Charlweed** [EngineHub/Piston#22]
New clone does not build from command-line or IntelliJ IDEA. What is required to build (on Linux)? 
Command line:
```
gradlew
FAILURE: Build failed with an exception.
* Where:
Build file '/usr/exports/projects/minecraft/Piston/core-ap/processor/build.gradle.kts' line: 35
* What went wrong:
kotlin.KotlinNullPointerException (no error message)
```

IDEA:
`Could not create parent directory for lock file ./Piston/?/.gradle/wrapper/dists/gradle-5.6.2-all/9st6wgf78h16so49nn74lgtbb/gradle-5.6.2-all.zip.lck`

**Comment by boy0001** [comment]
Dont use the intellij gradle wrapper, use the one in the repo.

**Comment by Charlweed** [comment]
Even without intellij, gradlew fails. 
I don't know any Kotlin, but tomorrow I will look at core-ap/processor/build.gradle.kts

**Comment by octylFractal** [comment]
If you can run it with `--stacktrace`, that would be appreciated.

**Comment by octylFractal** [comment]
I have found the issue -- it's the line requiring the current tools.jar to be present when building. Likely you are attempting to build on a JDK higher than 8, which is unsupported for now. Try setting your `JAVA_HOME` environment variable to a JDK 8 home environment. For example, on my system, `/usr/lib/jvm/java-1.8.0-openjdk-amd64`.

**Comment by octylFractal** [comment]
In addition, I have patched the project to build up to JDK 12. JDK 13 will require upgrading Gradle, but this project isn't targeted for higher JDKs anyways, so it's not urgent on my end. I will consider this fixed for now.

**Comment by Charlweed** [comment]
I concur, at least for the test of setting JAVA_HOME to a 1.8 JDK. I did not test with JDK 12.
