### ISSUE TITLE
Gradle scripts not outputting anything. (IntelliJ)

### ISSUE THREAD

**Issue by KingOfSquares** [EngineHub/Piston#27]
Hello!

Im trying to get a compiled JAR so i can use Piston to move a system away from Intake, since this seems more up to date.

When i run the Gradle scripts in IntelliJ the only thing that appears is a build folder with a kotlin folder which contains an empty sessions folder. Am i looking in the wrong place? Cant seem to find anything anywhere.

I get no errors when running the scripts. Thanks for any answers.

**Comment by wizjany** [comment]
Subprojects will be in their individual folders - core, core-ap, default-impl, etc.
