### ISSUE TITLE
MultiKeyConverter with `unknownValue` passed doesn't produce suggestions

### ISSUE THREAD

**Issue by me4502** [EngineHub/Piston#39]
When a MultiKeyConverter is created with an `unknownValue`, the conversion is considered successful and therefore further suggestions are never produced.

A potential idea for a fix is to have a "PartialSuccessfulConversion" that is successful but still causes suggestions to be produced.

Causes https://github.com/EngineHub/WorldEdit/issues/2357

**Comment by octylFractal** [comment]
Fixed by #42
