### ISSUE TITLE
No way to register a converter key with generic arguments

### ISSUE THREAD

**Issue by me4502** [EngineHub/Piston#44]
It is currently impossible to register a converter key that includes a generic argument. 

```
commandManager.registerConverter(Key.of(new TypeToken<SomeClass<?>>() {}), new SomethingConverter());
```

This appears to strip the `<?>` and error when attempting to use `SomeClass<?>` as a key in a command. It continues to only support the raw type, which is incompatible with `-Werror` as the generated classes fail due to rawtypes.

**Comment by octylFractal** [comment]
Not an actual bug, user error :^)
